module.exports = {
  CREATE_USER: ['OWNER'],
  CREATE_VEHICLE: ['OPERATOR', 'COORDINATOR'],
  UPDATE_VEHICLE: ['OPERATOR', 'COORDINATOR'],
  VIEW_VEHICLES: ['OWNER', 'OPERATOR', 'COORDINATOR'],

  UPLOAD_DOCUMENT: ['OPERATOR', 'COORDINATOR'],
  VIEW_DOCUMENTS: ['OWNER', 'OPERATOR', 'COORDINATOR'],

  CREATE_CHECK: ['OWNER'],
  VIEW_CHECKS: ['OWNER'],

  VIEW_AUDIT: ['OWNER']
}