module.exports = {
  CREATE_USER: ['CHEFE'],
  CREATE_VEHICLE: ['COLABORADOR', 'COORDENADOR'],
  UPDATE_VEHICLE: ['COLABORADOR', 'COORDENADOR'],
  VIEW_VEHICLES: ['CHEFE', 'COLABORADOR', 'COORDENADOR'],

  UPLOAD_DOCUMENT: ['COLABORADOR', 'COORDENADOR'],
  VIEW_DOCUMENTS: ['CHEFE', 'COLABORADOR', 'COORDENADOR'],

  CREATE_CHECK: ['CHEFE'],
  VIEW_CHECKS: ['CHEFE'],

  VIEW_AUDIT: ['CHEFE']
}